### ISSUE TITLE
[Bug]: No bindings for C#

### ISSUE THREAD

**Issue by DmitriySalnikov** [DmitriySalnikov/godot_debug_draw_3d#10]
### Godot version

4.x

### DebugDraw3D version

179ad806d520069e10ab6309cbb8799afc84d8c5

### Issue description

Due to differences in the work of GDExtension and the new versions of .NET in Godot, C# support was temporarily removed during porting.
To solve this, I need to either write a new API generator, or someone needs to extend the generator in the engine itself.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by DmitriySalnikov** [comment]
Following this [article](https://godotengine.org/article/whats-new-in-csharp-for-godot-4-0/#gdextension-support), API generation for C# is planned in future versions.
> Consuming APIs provided by a GDExtension is also currently unsupported. We’ll keep working on bridging the gap between GDExtension and C# in future 4.x releases.

**Comment by GeorgeS2019** [comment]
[Possible to create C# binding for GDExtension?](https://github.com/godotengine/godot-proposals/discussions/7024)

**Comment by wp2000x** [comment]
Are C# bindings now possible in GD 4.1?

**Comment by DmitriySalnikov** [comment]
Officially, there is no such possibility, but I haven't tried to make my own bindings yet. I heard that there were problems when trying to use classes from GDExtension in C#. I do not know whether it was fixed or not.

**Comment by GeorgeS2019** [comment]
@DmitriySalnikov 
I have done [further GDExtension c# Binding.](https://github.com/j20001970/GDMP-demo/discussions/6#discussioncomment-6403775) Not writing further to avoid Spanning impression

**Comment by DmitriySalnikov** [comment]
> I have done [further GDExtension c# Binding](https://github.com/j20001970/GDMP-demo/discussions/6#discussioncomment-6403775)

@GeorgeS2019 have you thought about starting to do PR for Godot with an API generator for GDExtension? Godot itself has this generator for a long time and it is used only when running with the `--generate-mono-glue` argument. All that is needed, it seems to me, is to run this generator for GDExtension through the editor, put the generated sources in a separate folder, compile them into a separate DLL and add this DLL as "friendly" (so that it can use `internal` classes) to the core of the Godot Mono library.

But, most likely, you need to create a `godot-proposal` first and discuss how best to do it with the Godot core team.

**Comment by GeorgeS2019** [comment]
@DmitriySalnikov Thx for your encouragement

**Comment by GeorgeS2019** [comment]
@DmitriySalnikov I saw u resume this recently. 

Are there still open issues?

**Comment by DmitriySalnikov** [comment]
I replied to a PR that allows me to reload libraries without having to restart the editor. With it, I could run the editor 1 time and rebuild the library several times.
Unfortunately this has nothing to do with C#.

**Comment by DmitriySalnikov** [comment]
@GeorgeS2019 
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/02860889-ea74-4585-8342-0bbc75ffa326)

Everything works again via `GodotObject.Call`, no native pointers, as in bindings for the engine. Therefore, I cannot guarantee high performance.
Bindings are generated manually by my generator.
The commit will be later.

**Comment by GeorgeS2019** [comment]
Native pointers

https://github.com/godotengine/godot-proposals/discussions/7024#discussioncomment-6851198

**Comment by DmitriySalnikov** [comment]
Isn't it about adding support for `NativeStucts` that were originally registered for `GDExtension`?
Like [`AudioFrame`](https://github.com/godotengine/godot/blob/fc99492d3066098e938449b10e02f8e01d07e2d1/core/register_core_types.cpp#L294)

**Comment by GeorgeS2019** [comment]
I will speak to him again

He understands very in depth what are missing now but beyond my understanding 

We are getting closer to the goal!

**Comment by DmitriySalnikov** [comment]
Nothing else is needed for my binding generator at the moment. After its release, I will wait for the official generator for `GDExtension <=> C#`. I'm not really interested in participating in adding an official feature right now.

**Comment by DmitriySalnikov** [comment]
I added a generator and updated the binaries. You can download the update here: https://github.com/DmitriySalnikov/godot_debug_draw_3d/archive/3c76608fd2409830bdbdd97a775d15ce5bef2202.zip

Also here the name `DebugDraw` was changed to `DebugDraw3D` and `DebugDraw2D`.

**Comment by GeorgeS2019** [comment]
Which Godot 4 version is used to open. It crashes using 4.2 Dev 4

**Comment by DmitriySalnikov** [comment]
What do you mean?
![Godot_v4 2-dev4_mono_win64_ZhATopaTlf](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/277c4608-017b-4410-8000-aae16fb082e3)

**Comment by GeorgeS2019** [comment]
Still trying to understand why the editor crashes using Godot4.2 Dev4

![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/49812372/b99834e9-99d5-419d-8c7e-5a422a0aa502)

**Comment by DmitriySalnikov** [comment]
> ![image](https://user-images.githubusercontent.com/49812372/267789578-b99834e9-99d5-419d-8c7e-5a422a0aa502.png)

Well, after this line, the generation of bindings should happen

**Comment by DmitriySalnikov** [comment]
updated libraries will be here https://github.com/DmitriySalnikov/godot_debug_draw_3d/actions/runs/6177991021
