### ISSUE TITLE
[Bug]: Error when running empty scene? 

### ISSUE THREAD

**Issue by en4ian** [DmitriySalnikov/godot_debug_draw_3d#11]
### Godot version

v4.0.2 stable.mono.official 7a0977ce2

### DebugDraw3D version

v1.0.0

### On which operating systems the error occurs

Windows

### Using which renderers the error occurs

Vulkan

### Issue description

scenes without a camera produce errors

### Steps to reproduce

I'm not sure which renderer I'm using but I assume it's Vulkan. I've never changed any settings for the renderer. I'm using Forward+

If I start a blank project, install debugdraw3d
then new empty scene based on Node3D - but do not add camera to scene
hit play
the console spits out errors

E 0:00:00:0764   DebugGeometryContainer::update_geometry: No camera found to perform frustum culling for DebugDraw
  <C++ Source>   src\debug_geometry_container.cpp:212 @ DebugGeometryContainer::update_geometry()

### Minimal reproduction project

n/a

**Comment by DmitriySalnikov** [comment]
yeap, I also ran into this today while I was updating another program.

**Comment by DmitriySalnikov** [comment]
I just removed this warning. d2310243625c058485228f0e30b119235b2c5e63
[GH Action for the test](https://github.com/DmitriySalnikov/godot_debug_draw_3d/actions/runs/4642351027)
