### ISSUE TITLE
[Feature Request]: Line Width

### ISSUE THREAD

**Issue by foureyedredheadedstepchild** [DmitriySalnikov/godot_debug_draw_3d#12]
### Feature description

Is it Possible to add a line width parameter?

**Comment by DmitriySalnikov** [comment]
Did you mean the same thing I described here? #3

**Comment by foureyedredheadedstepchild** [comment]
Yes ...my bad. ignore. would be a great feature though! considering it seems there's no out of the box way to this this without some hacky cube or billboard quad mesh type deal.

 anyway... you've explained it much better.

**Comment by DmitriySalnikov** [comment]
I close it as a duplicate #3

But at the moment I'm busy with Godot PCK Explorer, I can't figure out the encryption of PCK files in any way.
