### ISSUE TITLE
[Bug]: No way to enable the plugin

### ISSUE THREAD

**Issue by venilark** [DmitriySalnikov/godot_debug_draw_3d#13]
### Godot version

4.0.2

### DebugDraw3D version

1.1.0

### On which operating systems the error occurs

Windows

### Using which renderers the error occurs

Vulkan

### Issue description

![image](https://user-images.githubusercontent.com/98270528/234310897-f045957c-b54f-4725-a00c-97f36dccd8f8.png)
No option to enable the plugin to draw in the editor.

### Steps to reproduce

.

### Minimal reproduction project

.

**Comment by DmitriySalnikov** [comment]
It's not really a plugin... EditorPlugins in GDExtension are not working properly at the moment. Therefore, this addon is embedded in the editor using a hacks.
To check whether it is connected or not, you can simply search for `DebugDraw` in the built-in documentation. There should be a `DebugDraw` class (and several other classes) and a singleton.
Didn't you restart the editor after installation? Were there any errors in the console at startup?

**Comment by venilark** [comment]
> It's not really a plugin... EditorPlugins in GDExtension are not working properly at the moment. Therefore, this addon is embedded in the editor using a hacks. To check whether it is connected or not, you can simply search for `DebugDraw` in the built-in documentation. There should be a `DebugDraw` class (and several other classes) and a singleton. Didn't you restart the editor after installation? Were there any errors in the console at startup?

I just wanted to enable the debug lines in the Editor using Engine.is_editor_hint(), not in-game, which are already working.

**Comment by DmitriySalnikov** [comment]
> I just wanted to enable the debug lines in the Editor

Do you use the `@tool` annotation in your script? (as for example in `examples_dd3d/addon_icon.gd`)

**Comment by DmitriySalnikov** [comment]
Have you solved this issue?
I don't even understand the essence of the issue, since all my examples already work in the editor and in a running project.

**Comment by betalars** [comment]
> I don't even understand the essence of the issue, since all my examples already work in the editor and in a running project.

Cannot reproduce:

Steps:
 1. make empty project
 2. install your add-on
 3. restart the editor
 4. play your scene

What I got is an `DebugDrawConfig2D` not declared on line 15.

Sorry, but it really does not work right now in Godot4. I don't know what you did differently so it works for you. :thinking:

**Comment by DmitriySalnikov** [comment]
4.0.2
Just downloaded from AssetLib
Only the C# files have been deleted

![image](https://user-images.githubusercontent.com/7782218/235340584-b2a90c90-bb3d-48bf-b203-bf3e44a66b46.png)

![image](https://user-images.githubusercontent.com/7782218/235340588-58d54ac5-9c4d-4812-8efb-c27588ba81f2.png)

**Comment by betalars** [comment]
> Just downloaded from AssetLib

Did you do something else besides the steps I explained above? Is there ... idk ... some setting or ... I'm confused ...

**Comment by DmitriySalnikov** [comment]
For the ubuntu test, I even had to download the engine, because the system was almost empty.. And I just created the project and immediately entered AssetLib.
Can you show the console output (which runs through a separate exe)?

It seems to me that I have guessed what the problem is...
After viewing the contents of the console, try installing [vcredist](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022)

**Comment by betalars** [comment]
> Can you show the console output (which runs through a separate exe)?

```
Godot Engine v4.0.2.stable.custom_build - https://godotengine.org
OpenGL API 4.6 (Core Profile) Mesa 23.0.3 - Compatibility - Using Device: AMD - AMD Custom GPU 0405 (vangogh, LLVM 15.0.7, DRM 3.51, 6.1.21-valve1)
 
Editing project: /home/betalars/Development/godot/how-to-fly-your-dragon/src
ERROR: Can't open dynamic library: /home/betalars/Development/godot/how-to-fly-your-dragon/src/addons/debug_draw_3d/libs/libdd3d.linux.template_debug.x86_64.so. Error: libstdc++.so.6: cannot open shared object file: No such file or directory
   at: open_dynamic_library (drivers/unix/os_unix.cpp:447)
ERROR: GDExtension dynamic library not found: /home/betalars/Development/godot/how-to-fly-your-dragon/src/addons/debug_draw_3d/libs/libdd3d.linux.template_debug.x86_64.so
   at: open_library (core/extension/gdextension.cpp:400)
ERROR: Failed loading resource: res://addons/debug_draw_3d/debug_draw_3d.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:222)
ERROR: Error loading extension: res://addons/debug_draw_3d/debug_draw_3d.gdextension
   at: load_extensions (core/extension/gdextension_manager.cpp:120)
Godot Engine v4.0.2.stable.custom_build - https://godotengine.org

[betalars@steamDeck:~]$ Vulkan API 1.3.238 - Forward+ - Using Vulkan Device #0: AMD - AMD Custom GPU 0405 (RADV VANGOGH)
 
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:70)
SCRIPT ERROR: Compile Error: Identifier not found: DebugDraw
          at: GDScript::reload (res://examples_dd3d/DebugDrawDemoScene.gd:62)
SCRIPT ERROR: Compile Error: Identifier not found: DebugDraw
          at: GDScript::reload (res://examples_dd3d/addon_icon.gd:5)
```

**Comment by betalars** [comment]
Oops I forgot tho include the console out, how unprofesional :P

**Comment by DmitriySalnikov** [comment]
Probably the problem is that you are using an operating system with outdated `libstdc++` libraries. For example, my library is compiled on Ubuntu 22.04.2, and you have Ubuntu 20.04.6 installed. 

---

Oh, you're using SteamOS. I have no idea how to fix the problem. I've already spent 6 hours today trying to install another arch-based OS, and I'm already sick of it...

**Comment by DmitriySalnikov** [comment]
@venilark what about your problem?

**Comment by betalars** [comment]
> Probably the problem is that you are using an operating system with outdated `libstdc++` libraries.

okay will see where I can get libstdc++ 6 from then ...

**Comment by betalars** [comment]
Okay sorry, but this is not a practical option. I can technically create an environment where there are user level links for this library, but I'm afraid most users of arch derivates or nixos (in my case) won't be able to use your add-on then.

Can take some time later to think of a workaround, but for now I'll just be using ray casts... :P

**Comment by DmitriySalnikov** [comment]
> to think of a workaround

I haven't tested it yet, but it might be possible to statically link everything I need directly to the library so that it doesn't depend on other libraries. This is also relevant for `vcredist` on Windows..

**Comment by betalars** [comment]
Okay, yeah I hope this will be a good solution for compatibility.

And to summarize the actual issue:
Nixos does a lot of fancy things when it comes to providing libraries, and we're on a much newer version than Ubuntu, but your AddOn could simply not find it from it's scope.

So I'm using `steam-run godot` when launching godot to provide it with an environment that it will be happy with. It's kind of overkill, but it should resolve most dependency issues of these sorts.
