### ISSUE TITLE
[Bug]: Not working with Godot 4.1 RC1/2/3

### ISSUE THREAD

**Issue by diealp** [DmitriySalnikov/godot_debug_draw_3d#16]
### Godot version

4.1 RC3

### DebugDraw3D version

1.1.0

### On which operating systems the error occurs

macOS

### Using which renderers the error occurs

Vulkan

### Issue description

Installing the plugin manually or using the assetlib this is the console text:

  core/extension/gdextension.cpp:593 - GDExtension configuration file must contain a "configuration/compatibility_minimum" key: res://addons/debug_draw_3d/debug_draw_3d.gdextension
  Failed loading resource: res://addons/debug_draw_3d/debug_draw_3d.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
  res://examples_dd3d/addon_icon.gd:5 - Parse Error: Identifier "DebugDraw" not declared in the current scope.
  res://examples_dd3d/addon_icon.gd:6 - Parse Error: Identifier "DebugDraw" not declared in the current scope.
  res://examples_dd3d/addon_icon.gd:7 - Parse Error: Identifier "DebugDraw" not declared in the current scope.
  res://examples_dd3d/addon_icon.gd:7 - Parse Error: Identifier "DebugDraw" not declared in the current scope.
  res://examples_dd3d/addon_icon.gd:8 - Parse Error: Identifier "DebugDraw" not declared in the current scope.

and so on...

### Steps to reproduce

Install the plugin manually or via assetlib in Godot 4.1 RC 1/2/3

### Minimal reproduction project

N/A

**Comment by DmitriySalnikov** [comment]
Yes, because GDExtension 4.0 and 4.1 are not compatible. I will publish the update only after the release of Godot 4.1.

**Comment by diealp** [comment]
Ok, thanks!

**Comment by DmitriySalnikov** [comment]
https://godotengine.org/article/godot-4-1-is-here/

**Comment by diealp** [comment]
> https://godotengine.org/article/godot-4-1-is-here/

Great timing! :)

**Comment by DmitriySalnikov** [comment]
I apparently found where these errors came from. Now all methods returning `Object` try to get all bindings for specific classes in advance. Therefore, my `get_node`'s that are searching for a place of editor viewports cause a bunch of errors.
This happens even when I don't need anything more than a basic `Node`.

Perhaps this can be avoided, but most likely there may be more problems in other places.
So now the build time will increase 2-3 times for me, and the size of downloaded files will increase 2-3 times for users. 😥

**Comment by DmitriySalnikov** [comment]
37MB vs 101MB (86MB without `editor` libs as before)...
You can test library here (`gdextension_libs` asset):
https://github.com/DmitriySalnikov/godot_debug_draw_3d/actions/runs/5478565765

**Comment by diealp** [comment]
> 37MB vs 101MB (86MB without `editor` libs as before)...
> You can test library here (`gdextension_libs` asset):
> https://github.com/DmitriySalnikov/godot_debug_draw_3d/actions/runs/5478565765

i tried to replace the files under the libs directory but i still get the same errors, maybe i did something wrong

**Comment by DmitriySalnikov** [comment]
> maybe i did something wrong

No, this is my mistake, I forgot that I also updated the `.gdextension` file https://github.com/DmitriySalnikov/godot_debug_draw_3d/blob/47b686fcf8fe2597fbfd9095fd8f2afe4789d4d4/addons/debug_draw_3d/debug_draw_3d.gdextension

**Comment by diealp** [comment]
Yes! updating also the .gdextension file now it's working

**Comment by skooter500** [comment]
Hey

I cant get this to work on Windows Godot 4.1. It works on Godot 4.0

not enough arguments for format string
  platform/windows/os_windows.cpp:394 - Method/function failed. Returning: ERR_CANT_OPEN
  core/extension/gdextension.cpp:455 - GDExtension dynamic library not found: C:/Users/skooter500/Documents/courses/GE2-2023-GD4/GodotBoids/addons/debug_draw_3d/libs/libdd3d.windows.editor.x86_64.dll
  Failed loading resource: res://addons/debug_draw_3d/debug_draw_3d.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
  res://Boid.gd:34 - Parse Error: Identifier "DebugDraw" not declared in the current scope.

Bryan

**Comment by DmitriySalnikov** [comment]
Have you downloaded new [libraries](https://github.com/DmitriySalnikov/godot_debug_draw_3d/suites/14137179624/artifacts/791664469) and [.gdextension](https://github.com/DmitriySalnikov/godot_debug_draw_3d/blob/47b686fcf8fe2597fbfd9095fd8f2afe4789d4d4/addons/debug_draw_3d/debug_draw_3d.gdextension)?

I will update all the files in AssetLib later when I improve the patch to exclude unnecessary classes and turn the release libraries into dummies with a minimum size. I hope no one will need such debugging in the release versions of games, right?..

**Comment by skooter500** [comment]
Hey. I tested with Godot 4.1 and the new libraries and its working now. Also I would appreciate the ability to have these in release. I am making art and educational projects.

**Comment by DmitriySalnikov** [comment]
> Also I would appreciate the ability to have these in release.

What do you think about me leaving this option when manually compiling the library? Because I believe that most users will not need this feature in the release version.

Actually I can add separate versions of libraries
```ini
platform.template_release.DEBUG_DRAW_ENABLED.x86_64 = "libs/libdd3d.platform.template_release.DEBUG_DRAW_ENABLED.x86_64.**"
```
so that when specifying an additional tag `DEBUG_DRAW_ENABLED` during export, a library is used where `DebugDraw` is active.
But this will further increase the size of binaries that need to be downloaded for your project during development. For large projects, this is not a problem, but for small ones it is too much.

Although the best option would be if `Conditional Compilation` was finally added to `GDScript`, so that those who do not need `DebugDraw` in the release version could simply remove all mentions of it when compiling scripts/exporting game.

**Comment by wrightwriter** [comment]
thanks so much for the work! works in 4.1 here without issues after update

**Comment by StaleLoafOfBread** [comment]
The version in the main branch right now https://github.com/DmitriySalnikov/godot_debug_draw_3d/commit/9a0524709dd9cd8489921b7c4206e526ebd0d88f gives me error `error loading extension: res://addons/debug_draw_3d/debug_draw_3d.gdextension` with `v4.1.stable.official [970459615]`. Based on above [comments](https://github.com/DmitriySalnikov/godot_debug_draw_3d/issues/16#issuecomment-1635816396) it looks like it should be working. Am I misunderstanding?

**Comment by DmitriySalnikov** [comment]
I'm sorry that I haven't updated the binaries yet, I just don't know what to do with the large download size.

**Comment by diealp** [comment]
For me the separate versions is the solution

**Comment by StaleLoafOfBread** [comment]
> I'm sorry that I haven't updated the binaries yet, I just don't know what to do with the large download size.

Its all good. I was just confused since I saw other people say that 4.1 worked for them. GDExtension development is not something I am familiar with so I didn't realize the libraries wouldn't be in the repo itself. especially when some similar looking files were there.

**Comment by DmitriySalnikov** [comment]
> For me the separate versions is the solution

I updated the binaries and added a new section to the readme: https://github.com/DmitriySalnikov/godot_debug_draw_3d#exporting-a-project

**Comment by DmitriySalnikov** [comment]
The library has been updated on AssetLib
