### ISSUE TITLE
Adding Godot 4 Support

### ISSUE THREAD

**Issue by wp2000x** [DmitriySalnikov/godot_debug_draw_3d#2]

**Comment by DmitriySalnikov** [comment]
After a lot of confusion, I was able to build a library for godot 4.

![image](https://user-images.githubusercontent.com/7782218/197128681-7b20324a-16bc-41af-a3d6-c76dfed3d809.png)

But I haven't even tried to display anything yet. At the moment I can't even register any function with pointers.

![image](https://user-images.githubusercontent.com/7782218/197122431-69e3c6ee-67bd-4f85-b79b-a18015ddafdf.png)

Some of these functions can be ignored, but the problem still remains. `Callable::bind()` is still unavailable, but it can also be avoided.

I also need to rethink how to initialize the displaying of everything. Previously, a node was simply created, now I want to use a singleton that is not added to the scene...

**Comment by ExquisiterEmil** [comment]
I think this will be extremely useful, so I would very much look forward to Godot 4 support :D

**Comment by DmitriySalnikov** [comment]
With some patches and hacks, I was finally able to see at least such a graph
![image](https://user-images.githubusercontent.com/7782218/206897694-14fb4a02-8bb1-4faf-9529-ab6087f81e3b.png)

**Comment by DmitriySalnikov** [comment]
![image](https://user-images.githubusercontent.com/7782218/207424641-a564e826-2d89-44e2-ae14-757ff3dfb516.png)

**Comment by wp2000x** [comment]
I wanted to try out the CI build but get this error, any ideas why?(https://github.com/DmitriySalnikov/godot_debug_draw_3d/actions/runs/3688845973)

![image](https://user-images.githubusercontent.com/70962730/208139430-f4be8ad3-e43b-49fb-9f60-4d9c1480b598.png)

**Comment by DmitriySalnikov** [comment]
@wp2000x As I mentioned in the comment to this commit 7133097220b78d931d405a5db56ca4e071e6c7bf, you need a newer version of Godot. Beta 8 doesn't include this change yet.
Use for example this version: https://github.com/godotengine/godot/actions/runs/3714553342
But don't expect this addon to work correctly. It's currently has problems with centering boxes, clearing memory when closing, clearing geometry when switching scenes, and many other problems.

I will try to fix them as soon as I solve the problem with a completely broken and **reinstalled** Windows...

**Comment by DmitriySalnikov** [comment]
I haven't started working on the C# wrapper yet. I just decided not to delete this `.cs` file, even though it was generated by a script that no longer exists.

https://github.com/DmitriySalnikov/godot_debug_draw_3d/blob/d6b0fd70d124e278c78705225e7ba6408849c1a2/addons/debug_draw_3d/DebugDrawCS.cs#L9-L13

I'll see what I can do about it later. I need to check how C# code generators work and whether they can generate code from `GDExtension`. If not, then I will now be able to generate the `.cs` API file from `ClassDB` without any problems 🙂 (except that I do not know how to add documentation there).

**Comment by DmitriySalnikov** [comment]
One more issue:
* https://github.com/godotengine/godot/issues/71897

**Comment by wp2000x** [comment]
> I haven't started working on the C# wrapper yet. I just decided not to delete this `.cs` file, even though it was generated by a script that no longer exists.
> 
> https://github.com/DmitriySalnikov/godot_debug_draw_3d/blob/d6b0fd70d124e278c78705225e7ba6408849c1a2/addons/debug_draw_3d/DebugDrawCS.cs#L9-L13
> 
> I'll see what I can do about it later. I need to check how C# code generators work and whether they can generate code from `GDExtension`. If not, then I will now be able to generate the `.cs` API file from `ClassDB` without any problems 🙂 (except that I do not know how to add documentation there).

Great! Im waiting eagerly, so that i can re-intergrate it into my GD4 C# project. Any ETA? 😄 
I didn't saw any C# code generation in Godot for custom engine extenstions, so ClassDB came into my mind how to connect it. But that is also not really working.

**Comment by DmitriySalnikov** [comment]
> I didn't saw any C# code generation in Godot for custom engine extenstions

I found that it is possible to do so https://www.reddit.com/r/godot/comments/zlglpk/comment/j081fkm/?utm_source=share&utm_medium=web2x&context=3
But it doesn't work correctly..
Maybe I can find out from there how to make a good binding generator.

At the moment I want to add a small optimization of instances data transfer to Godot.
After that, I will either try to fix memory leaks when closing the engine, or add a C# wrapper.

And it would also be interesting how difficult and whether it is even possible to add support for other C++ libraries (use `debug_draw_3d` from another `GDExtension` library).

**Comment by wp2000x** [comment]
Ah, good to know, that the mono glue generator also tries to generate it for extenstions. I also found this: https://github.com/antonWetzel/GDExtensionCSharp maybe it will help you as a base for a binding generator.

**Comment by DmitriySalnikov** [comment]
If I understand correctly, this is not what I need. Here the developer makes an alternative to `godot-cpp` but in C#. But I may still study this repository if I encounter some problems. Thanks.

**Comment by DmitriySalnikov** [comment]
`--generate-mono-glue` can't even generate mono glue for me
```
C:\My\Godot\godot_v4.0\beta15\Godot_v4.0-beta15_mono_win64.exe --project "C:\My\Projects\GE\DebugDraw3D 4.0\project.godot" --generate-mono-glue .
```

```
$ Godot Engine v4.0.beta15.mono.official.4fa6edc88 - https://godotengine.org
Vulkan API 1.3.224 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 970

Ignoring type 'AnimationNodeEndState' because it's not exposed
Ignoring type 'AnimationNodeStartState' because it's not exposed
Ignoring type 'CreateDialog' because it's not exposed
ERROR: FATAL: Condition "r_iarg.type.cname != name_cache.type_String" is true.
   at: _arg_default_value_from_variant (modules/mono/editor/bindings_generator.cpp:3272)
```

Now I need to understand where I use `NodePath` at all... and why is the name of this class not equal to `String`

**Comment by DmitriySalnikov** [comment]
I got a dll with bindings for `debug_draw_3d`. It remains to connect them correctly to the project.

**Comment by DmitriySalnikov** [comment]
### "Simple" instructions for API generation:
* Clone the godot repository.
* [Build an engine from sources](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_with_mono.html) or use pre-build binaries from the news
* Run `"path to the godot's exe" --headless --project "path to the project with .gdextension\project.godot" --generate-mono-glue "path to cloned repository\modules\mono\glue"`
* Following [this documentation](https://github.com/godotengine/godot/blob/master/modules/mono/README.md), you need to add a local NuGet source: `dotnet nuget add source "absolute path to the local nuget source" --name MyLocalGodotSource`
* Build C# assemblies: `cd "path to cloned repository"` then `"modules/mono/build_scripts/build_assemblies.py" --godot-output-dir=./bin --godot-platform=windows --push-nupkgs-local "absolute path to the local nuget source"`
* Clear the folder `.godot/mono` inside the project
* You may need to clear the nuget cache manually. Delete a folder `%appdata%\Godot\mono\GodotNuGetFallbackFolder`

I hope I didn't miss anything. But I don't like this solution. Maybe if you have a lot of `.gdextension`s and if you have worked with the godot builds, then this will be the easiest and most convenient way to add the C# API, but do it only for the sake of one extension.....

**Comment by wp2000x** [comment]
Nice! Will test it out. Would it maybe make sense to ship a pre-generated nuget for every DebugDraw version release on nuget.org for this approach?

**Comment by DmitriySalnikov** [comment]
> The local nuget source is there but the DebugDraw interface classes are not recognized. Deleting .godot/mono and %appdata%\\Godot\\mono\\GodotNuGetFallbackFolder does not help.

I also faced this and struggled with it for a while. Clearing all caches and recreating the C# project helped me (maybe I did something else).

I have already asked a question in godot's RocketChat about generating an API for GDExtension, but there has been no answer yet. Most likely I will have to write a proposal.
My plan for now is to make my own C# API generator (or copy it from Godot) until the official one appears.

But unfortunately I can't develop the project yet. My PC's PSU failed and I'm without a PC until at least February 3rd.

But if you manage to use local nuget packages, then you can safely use them, because I will try to make the generator as close as possible to the Godot generator. And most likely it will be just a .cs file inside your project again.

**Comment by wp2000x** [comment]
I tried further, but still the same. Guess i will wait for your API generator.
Good idea with the proposal, something like this would be very nice when implemented out of the box.
Good luck with your PSU 😄

**Comment by DmitriySalnikov** [comment]
I found one annoying problem. The entire C# API consists of unsafe code.
This means that users of this extension will need to enable this checkbox if I generate a `.cs` file with API inside project.
![image](https://user-images.githubusercontent.com/7782218/216621162-19469f29-ed40-4d1f-8107-0393068d1b2e.png)
Otherwise, you will need to add a precompiled library... Which also forces you to edit the project settings.

**Comment by DmitriySalnikov** [comment]
I tried several options with changing the original generator to support `GDExtension` API generation, but nothing worked. Even if you get direct access to all the `internal` methods and classes of `GodotSharp.dll` ([InternalsVisibleToAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?view=net-7.0)), there will still be problems with the Godot's SourceGenerator.
I will have to make my own generator from scratch and without maximum performance of `GodotSharp.dll`, or I'll just postpone C# support for now.

I want to release a GDScript-only version first. And if no one has created a proposal yet, then I need to write it as well.

**Comment by DmitriySalnikov** [comment]
I think the porting is complete.
I have collected the remaining issues into a separate topic. #9

**Comment by GeorgeS2019** [comment]
@DmitriySalnikov 

This could be [a possible way](https://github.com/j20001970/GDMP-demo/discussions/6#discussioncomment-6029012) to deal with GDExtensiong binding for c# based on ideas from **[LibGodotSharp](https://github.com/RhubarbVR/LibGodotSharp/blob/main/sharp_generator/Program.cs#L171)**

**Comment by DmitriySalnikov** [comment]
@GeorgeS2019 I noticed only a copy paste of my solution there, the rest will not help me in any way. But if I understood everything correctly, then you have confused `GlobalClass` with bindings for `GDExtension`.
As @j20001970 said:
> it is about allowing C# classes to be registered as global classes (similar to Autoload in GDScript), not using GDExtension classes in C#

I would say that `GlobalClass` is an analog of `class_name` from `GDScript`.
And I agree with him that at the moment it is better to wait until the official support for `GDExtension` in `C#` appears. Or you can help Godot with the implementation of this feature.

**Comment by GeorgeS2019** [comment]
@DmitriySalnikov 

[This](https://github.com/DmitriySalnikov/godot_debug_draw_3d/issues/2#issuecomment-1567086758) is **separate** from the GlobalClass c# discussion

Here is the [discussion](This is the [link](https://github.com/j20001970/GDMP-demo/discussions/6#discussioncomment-6029012))

Using the **available** c# binding GDExtension codes in LibGodotSharp repos, I think with some modications, it can be used in e.g. Godot Debug Draw GDExtension for c#

 [sharp_generator](https://github.com/RhubarbVR/LibGodotSharp/tree/main/sharp_generator)


=> **Step1** Start with a godot repos with c++ GDExtension, create the `--dump-extension-api`

##### [reference1](https://github.com/RhubarbVR/LibGodotSharp/blob/9019f8c187333e27d4526f461e79727be89c5413/sharp_generator/Program.cs#L129)
`godotBinary --dump-extension-api --verbose --headless`

=> **Step2** From the json files, deserialize. 
=> **Step3** Separate those class of GDExtension from the core. 
=> **Step4** Create the c# interop native class needed to bind the c++ class from GDExtension.
=> **Step5** Compile these c# interop class against the GodotSharp from the code to create c# GDExtension nuget 
 
```cs
//var api = JsonSerializer.Deserialize<GDApi>(file);
var api = Api.Create(pathToGenJson);
var convert = new Convert(api, ginDir, docs, configName);
convert. Emit();
```

**Comment by DmitriySalnikov** [comment]
Do you mean compiling the entire C# interop code only with my bindings (`GodotSharp.dll` and all tools libs)? Or only `GodotSharp.dll` with only my classes?

In the first case, it seemed to me that `Godot.exe` can only load specific predefined DLLs. And I am not sure that I will be able to load and use a full-fledged separate C# interop.
And in the second case with generation only `GodotSharp.dll`, I have already tried and faced a bunch of problems and errors. I tried to duplicate the C# interop generator from the Godot module, cutting out all unnecessary and replacing some names with my own so that there would be no conflicts.

Do you already have a ready-made prototype with the implementation of your ideas? I would be interested to see it.

**Comment by GeorgeS2019** [comment]
@DmitriySalnikov 
I believe this is the current status for GDExtension for c#
https://github.com/godotengine/godot/pull/77410#issuecomment-1561883694

**Comment by DmitriySalnikov** [comment]
Isn't this a "standard" fix for casting Objects from an internal Godot type to an external GDExtension or C#? (they just tried to fix it several times already)
Also [here](https://github.com/godotengine/godot/pull/77410/files#diff-af904e3529e788ec295578f68561554dd3caf3d290fa274e75d83b43e500d01f) is the `binding generator` which was mentioned in the comments there.

**Comment by GeorgeS2019** [comment]
@DmitriySalnikov 

https://github.com/antonWetzel/GDExtensionCSharp/issues/1#issuecomment-1576276659

```cs
namespace GDMP {
    class SomeCoolObject {
        private GD.Object data;
         
        public SomeCoolObject() { this.data = GD.Instantiate("GDMPSomeCoolObject"); }

        public SomeType SomeFunction() {
            return (SomeType)this.data.call("some_function");
        }
    }
}
```

**Comment by DmitriySalnikov** [comment]
`GDExtensionCSharp` is also not a `GDExtension` binding generator for `C#`.. This is an implementation of `C#` support via `GDExtension`.
If you are interested, then this is how it was implemented for a long time in my `GDNative` version for Godot 3: https://github.com/DmitriySalnikov/godot_debug_draw_3d/blob/godot_3/addons/debug_draw_3d/DebugDrawCS.cs.
This can also be implemented now, but this is a very bad way of calling methods, because every time there is a comparison of strings with method names, type conversions to variant and back. Whereas official bindings use lower-level method calls.

**Comment by GeorgeS2019** [comment]
@DmitriySalnikov 

Instead of Godot3 loading NativeScript
`debug_draw_3d = ResourceLoader.Load<NativeScript>("res://addons/debug_draw_3d/libs/debug_draw_3d.gdns").New() as Node;`

Use Godot4 GDExtension to Open xxxx.dll

```cs
//GDExtension.cs

namespace Godot;

using System;
using System.Diagnostics;
using Godot.NativeInterop;

#pragma warning disable CS1591 // Disable warning: 'Missing XML comment for publicly visible type or member'
#pragma warning disable CS1573 // Disable warning: 'Parameter has no matching param tag in the XML comment'

#nullable disable
public partial class GDExtension : Resource
{
    public enum InitializationLevel : long
    {
        Core = 0,
        Servers = 1,
        Scene = 2,
        Editor = 3
    }

    private static readonly System.Type CachedType = typeof(GDExtension);

    private static readonly StringName NativeName = "GDExtension";

    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private static readonly unsafe delegate* unmanaged<IntPtr> NativeCtor = ClassDB_get_constructor(NativeName);

    public GDExtension() : this(true)
    {
        unsafe
        {
            _ConstructAndInitialize(NativeCtor, NativeName, CachedType, refCounted: true);
        }
    }

    internal GDExtension(bool memoryOwn) : base(memoryOwn) {}

    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private static readonly IntPtr MethodBind0 = ClassDB_get_method(NativeName, MethodName.OpenLibrary);

    public Error OpenLibrary(string path, string entrySymbol)
    {
        return (Error)NativeCalls.godot_icall_2_268(MethodBind0, GodotObject.GetPtr(this), path, entrySymbol);
    }

    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private static readonly IntPtr MethodBind1 = ClassDB_get_method(NativeName, MethodName.CloseLibrary);

    public void CloseLibrary()
    {
        NativeCalls.godot_icall_0_3(MethodBind1, GodotObject.GetPtr(this));
    }

    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private static readonly IntPtr MethodBind2 = ClassDB_get_method(NativeName, MethodName.IsLibraryOpen);

    public bool IsLibraryOpen()
    {
        return NativeCalls.godot_icall_0_33(MethodBind2, GodotObject.GetPtr(this)).ToBool();
    }

    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private static readonly IntPtr MethodBind3 = ClassDB_get_method(NativeName, MethodName.GetMinimumLibraryInitializationLevel);

    public GDExtension.InitializationLevel GetMinimumLibraryInitializationLevel()
    {
        return (GDExtension.InitializationLevel)NativeCalls.godot_icall_0_36(MethodBind3, GodotObject.GetPtr(this));
    }

    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private static readonly IntPtr MethodBind4 = ClassDB_get_method(NativeName, MethodName.InitializeLibrary);

    public void InitializeLibrary(GDExtension.InitializationLevel level)
    {
        NativeCalls.godot_icall_1_35(MethodBind4, GodotObject.GetPtr(this), (int)level);
    }

    protected internal override bool InvokeGodotClassMethod(in godot_string_name method, NativeVariantPtrArgs args, out godot_variant ret)
    {
        return base.InvokeGodotClassMethod(method, args, out ret);
    }

    protected internal override bool HasGodotClassMethod(in godot_string_name method)
    {
        return base.HasGodotClassMethod(method);
    }

    protected internal override bool HasGodotClassSignal(in godot_string_name signal)
    {
        return base.HasGodotClassSignal(signal);
    }

    public new class PropertyName : Resource.PropertyName
    {
    }

    public new class MethodName : Resource.MethodName
    {
        public static readonly StringName OpenLibrary = "open_library";
        public static readonly StringName CloseLibrary = "close_library";
        public static readonly StringName IsLibraryOpen = "is_library_open";
        public static readonly StringName GetMinimumLibraryInitializationLevel = "get_minimum_library_initialization_level";
        public static readonly StringName InitializeLibrary = "initialize_library";
    }

    public new class SignalName : Resource.SignalName
    {
    }
}

#pragma warning restore CS1591
#pragma warning restore CS1573
```

**Comment by DmitriySalnikov** [comment]
too much off topic
