### ISSUE TITLE
API documents seems not work?

### ISSUE THREAD

**Issue by shaoway** [DmitriySalnikov/godot_debug_draw_3d#21]
Ctrl+click the DebugDraw, the editor jump to a empty page.
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/80565033/21aea4b4-9c97-45d2-a933-1144e315231f)

Something goes wrong?

**Comment by DmitriySalnikov** [comment]
You ignored the bug report template, so I don't even know the engine and library versions.

---

`DebugDraw` `1.1.3` from AssetLib

4.1

https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/bf6f7208-0bfd-49f4-bb54-847203d5717b

4.1.1

https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/db08e06b-3a93-459b-a9b5-aca61c1cc2fd

4.2.dev2

https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/72368a15-30dc-435f-9019-837057c9ba84

**Comment by shaoway** [comment]
I'm using godot 4.1.1. So I think I'm using the wrong version of lib.
Thanks for reply.

**Comment by DmitriySalnikov** [comment]
Did you manage to fix the problem?

**Comment by shaoway** [comment]
> Did you manage to fix the problem?

Yeah. By reinstall it from Godot's AssetLib.
