### ISSUE TITLE
[Feature Request]: Drawing Planes

### ISSUE THREAD

**Issue by PauloVBettio** [DmitriySalnikov/godot_debug_draw_3d#32]
### Feature description

Include a method for drawing [Plane](https://docs.godotengine.org/en/stable/classes/class_plane.html)s. This would be very helpful to visualize mouse interaction on 3D when using planes.

### Implementation Ideas

Introduce a new method, such as draw_plane, that takes a Plane as a parameter. This method would then render a visual representation of the plane in the 3D space.

`DebugDraw3D.draw_plane(plane, color, duration)`

**Comment by DmitriySalnikov** [comment]
Does this look like what you expected?

https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/7ee2f8cc-4f3d-48a1-be87-490ceead8fe4

But I added another argument to specify a point that is projected onto the plane to find the center of the plane model instance.
`DebugDraw3D.draw_plane(plane, color, anchor_point, duration)`

https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/7ff7b61c-4bf5-419b-9ff6-f42b0691a9ef

By default, the position of the current camera and its `Far` parameter are used to specify the position and size of the plane.

https://dd3d.dmitriysalnikov.ru/dev/volumetric/docs/classDebugDraw3D.html#aa127e9bc9816e73d08d79f87ddc22e43

**Comment by PauloVBettio** [comment]
That is great and very helpful, thanks so much!

**Comment by DmitriySalnikov** [comment]
Now all that's left is to finish 1.3.0...😅

And fix the tilt of the plane in some positions:
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/26fe202c-ef6e-4d7f-ad71-30a3f1204e8b)
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/34de294c-3051-4bf7-a933-5810afd38bc2)

**Comment by DmitriySalnikov** [comment]
Implemented in 361cc942ccbb84791983d91c1a58c1f38134d333
