### ISSUE TITLE
[Bug]: Macos Arm64 Support

### ISSUE THREAD

**Issue by QuentinWidlocher** [DmitriySalnikov/godot_debug_draw_3d#34]
### Godot version

4.2.1 stable

### DebugDraw3D version

1.3.0

### On which operating systems the error occurs

macOS

### Issue description

Maybe I'm missing something, but adding the `debug_draw_3d.gdextension` in the addons folder yields this error message when restarting godot:

```
core/extension/gdextension.cpp:911 - No GDExtension library found for current OS and architecture (macos.arm64) in configuration file: res://addons/debug_draw_3d/debug_draw_3d.gdextension

Failed loading resource: res://addons/debug_draw_3d/debug_draw_3d.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
```

[This two month old reddit post](https://www.reddit.com/r/godot/comments/17vanuw/on_mac_are_gdextensions_downloaded_from_the/) seems to indicate this addons isn't compatible with mac M1/2/3 ? I have a Macbook Air M2.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by DmitriySalnikov** [comment]
Can you try changing all the `.gdextension` lines that start with `macos = ` to `macos.arm64 = `?

**Comment by ALapidis** [comment]
Tried the new file, renamed to gdextension and restarted godot. Still getting:
```
 core/extension/gdextension.cpp:911 - No GDExtension library found for current OS and architecture (macos.x86_64) in configuration file: res://addons/debug_draw_3d/debug_draw_3d.gdextension
  Failed loading resource: res://addons/debug_draw_3d/debug_draw_3d.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
```

**Comment by DmitriySalnikov** [comment]
Were there any other errors before this error?

**Comment by ALapidis** [comment]
No, this is the only error that appears int he console output as soon as the project loads. I've already commented out all calls or references to the old classes.

**Comment by ALapidis** [comment]
Added it to a blank project via the AssetLib, same error (but also spam about the example file calling methods that dont' exist yet).

**Comment by DmitriySalnikov** [comment]
I definitely ran GDExtension earlier by specifying `.dylib`.., but the example specifies the `.framework` folder. https://github.com/godotengine/godot-cpp/blob/dd62b9685fbc9b733a25e26a788b5d7f3212a804/test/project/example.gdextension#L8
I will be able to create these templates later.

or perhaps you can remove the `.dylib` extension from the path 🤷‍♂️

**Comment by ALapidis** [comment]
No luck, tried to remove the .dylib from the path. Same error.
Tried to copy/paste the contents of the earlier gdextension you linked, same error.

**Comment by DmitriySalnikov** [comment]
With the updated `.gdextension` from the previous comment, I was able to run the editor on Monterey x86_64.

![vmware_kke6suNTGL](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/f8175162-0024-40ec-a003-f6c9e35e5ae8)

**Comment by ALapidis** [comment]
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/16485257/f13a51df-616e-4b96-b2af-51f7a7a86a61)
Could it be with Sonoma?

**Comment by ALapidis** [comment]
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/16485257/d1fc7aed-3324-492d-8b5f-2ee05165a03c)
Could it have anything to do with Sonoma?

**Comment by ALapidis** [comment]
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/16485257/275470f4-0be2-4609-98c9-ba85b621301d)
Could it have anything to do with Sonoma? Here are my specs.

**Comment by ALapidis** [comment]
Here is the output of a fresh install from assetLib and replaced the gdextension file with the one linked in the previous post.
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/16485257/e1a9815a-25fb-481d-ab14-5f0f9ddaa555)

**Comment by DmitriySalnikov** [comment]
> Could it have anything to do with Sonoma?

Only if apple disallowed direct use of the combined libraries.

> replaced the gdextension file with the one linked in the previous post.

No no, I meant my `.gdextension` https://github.com/DmitriySalnikov/godot_debug_draw_3d/issues/34#issuecomment-1879383721
That file from the example cannot be run with my libraries at all.

**Comment by ALapidis** [comment]
Ah I see, my mistake. Yes that one seems to work now. Which is odd because last night I tried it as well, fresh install, download the .txt and rename it in get info, <shrug> but it seems to work now.

**Comment by DmitriySalnikov** [comment]
> seems to work now

While testing I had a similar problem. I updated the file, restarted the project in the virtual machine and nothing worked, although the file seemed to be updated. From the second start the library started working 🤷‍♂️

> but it seems to work now. Thankyou!

That's good to hear!

It would also be nice to know if the library works with arm64. @QuentinWidlocher, does the library work with arm64 and updated `.gdextension`?

**Comment by QuentinWidlocher** [comment]
I created a new project, downloaded the addon from the asset store and the replaced the `debug_draw_3d.gdextension` by the one you provided in your comment. I still have the same exact error when opening the demo scene in the addon

<img width="918" alt="image" src="https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/51164641/73238f1f-4675-4604-bccf-74b16280f86c">

You both seem to have no problem on x86 macos, but even if the universal build should work with arm64, it doesn't for me 😕

**Comment by DmitriySalnikov** [comment]
So if you actually have those lines in the `.gdextension` file, then I can only suggest restarting the editor again for now 🤷‍♂️.
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/a8b3ec9b-ceee-4593-a3aa-dccf9cdb8aed)

**Comment by nerolapis** [comment]
In my case (M1 Max), the architecture configuration issue was solved by inverting the order of the macOS related lines from

```
# debug

macos.arm64 = "libs/libdd3d.macos.editor.universal.dylib"
macos.x86_64 = "libs/libdd3d.macos.editor.universal.dylib"
```

to

```
# debug

macos.x86_64 = "libs/libdd3d.macos.editor.universal.dylib"
macos.arm64 = "libs/libdd3d.macos.editor.universal.dylib"
```

and restarting the editor.

**Comment by DmitriySalnikov** [comment]
> by inverting the order of the macOS-related lines from

oooh.. That's really bad.
Because if you change their order, then the library is no longer recognized in x86_64.

**Comment by nerolapis** [comment]
I see. This seems more like a Godot-related issue in reading the extension configuration file. 
Until it is corrected, we could invert the order to have the extension working, waiting for the main fixing to arrive.

**Comment by DmitriySalnikov** [comment]
> [!IMPORTANT]
> Comments in `.gdextension`/`ConfigFile` - [` ; `](https://docs.godotengine.org/en/latest/classes/class_configfile.html#:~:text=with%20a%20semicolon%20(-,%3B,-).%20Those%20lines%20will)
> Not - `#`
>
> Even if the `ConfigFile`s format seems to be completely similar to ini, in which [` # `](https://en.wikipedia.org/wiki/INI_file#:~:text=foo%20%3D%20bar-,%23,-This%20is%20another) is a comment too.

**Comment by nerolapis** [comment]
Can confirm that by replacing `#`s with `;` for comments, the config file works even without inverting the order of the macOS-related lines 🎉 

So we will not have to _wait for Godot_ after all 😀

**Comment by DmitriySalnikov** [comment]
Huge FPS!

https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/987e05b9-dc4b-4392-a95b-de10d818b840

Btw [1.3.1](https://github.com/DmitriySalnikov/godot_debug_draw_3d/releases/tag/1.3.1) is already available.
