### ISSUE TITLE
[Feature Request]: DebugDraw2D should be visible on 2D viewport too

### ISSUE THREAD

**Issue by JUSTCAMH** [DmitriySalnikov/godot_debug_draw_3d#37]
### Feature description

Currently all the functions in DebugDraw2D draw to the 3D viewport, and don't show anything in the 2D viewport. As the class is called DebugDraw2D, I had expected these functions would be useful for my 2D game, but alas this is not the case, I can see it in 3D but not in 2D.

### Implementation Ideas

Functions in DebugDraw2D should draw to both the 2D and 3D viewports, so that they can be viewed in both the 2D and 3D editor tabs.

**Comment by DmitriySalnikov** [comment]
You mean 2d and 3d tabs in the editor?
If so, there's [set_custom_canvas](https://dd3d.dmitriysalnikov.ru/docs/1.3.1/classDebugDraw2D.html#a0b111f429b856cb93df850211e620238) for that. But that would allow drawing exactly on the canvas node, not the overlay in the editor, although you could try to get a 2d viewport of the editor.

**Comment by JUSTCAMH** [comment]
Ahh, that is what I meant, thanks! And I believe the answer is no, but is it possible to draw lines, circles and other guides in the 2D tab?

**Comment by DmitriySalnikov** [comment]
> And I believe the answer is no, but is it possible to draw lines, circles and other guides in the 2D tab?

Not yet. The library was originally planned for 3d, so 2d wasn't a priority. Also currently I don't see support for this library from the community (but people use this library quite a bit) and I have no motivation right now to add support for 2d shapes.

**Comment by JUSTCAMH** [comment]
Ok thanks, totally understandable!

**Comment by JUSTCAMH** [comment]
For anyone else looking, godot actually has some really great built in tools for this in 2D: https://docs.godotengine.org/en/stable/tutorials/2d/custom_drawing_in_2d.html

**Comment by DmitriySalnikov** [comment]
Yes it does. But to do this, you need to create separate variables with states inside the class and use a `_draw` method.
Therefore, if I ever start working on adding 2D shapes to this library, then all the logic with `_draw` and separate variables will be hidden from the user and you will just need to call `DebugDraw2D.draw_line(a, b, Color.RED)`.
But I'm not really sure yet how the camera behavior, zooming, and other things will be handled.
