### ISSUE TITLE
[Bug]: Rotation of DebugDraw3D.DrawBox() draws a warped/flattened box.

### ISSUE THREAD

**Issue by JakeRabinowitz** [DmitriySalnikov/godot_debug_draw_3d#38]
### Godot version

v4.2.1.stable.mono.official [b09f793f5]

### DebugDraw3D version

1.3.1

### On which operating systems the error occurs

Windows

### Issue description

Applying rotation to DrawBox3D() results in unexpected deformation/warping of the box.

![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/1495255/a7b94e3e-563e-4521-8d2c-06e2f1182952)

# Video:
https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/1495255/304c17c2-1cd6-4d4b-9cd1-79d3c0c2c758

### Steps to reproduce

1. Create a new Node3D and attach a new C-Sharp Script to it.
2. Mark the script as [Tool] and add the following code:
3. ```csharp

	public override void _Process(double delta)
	{
		Vector3 size = new Vector3(8, 1, 4);
		Quaternion rotation = Quaternion.FromEuler(new Vector3(0, 0, 45));
		DebugDraw3D.DrawBox(Vector3.Zero, rotation, size, new Color(0x00FF00FF), true);
	}
	```

You will see that the box is warped and no longer a rectangle.

**Expected Result**
The box should be rotated and still rectangular, the same way that a BoxMesh would be.

### Minimal reproduction project

[DrawBox3DBug.zip](https://github.com/DmitriySalnikov/godot_debug_draw_3d/files/14501791/DrawBox3DBug.zip)

* Note: You might need to close & reopen the main.tscn for the box to render.

**Comment by DmitriySalnikov** [comment]
This is the current implementation:
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/bb02dd8f-6477-421a-90c8-15c9ba8f0388)

And this is what I suppose it should look like?
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/399ff10b-1e22-4e7c-8fea-d63ae7308449)

Also, the correct indication of the 45 degree angle is:
```gdscript
var rot = Quaternion.from_euler(Vector3(0, 0, PI/4))
#or
var rot = Quaternion.from_euler(Vector3(0, 0, deg_to_rad(45)))
```

**Comment by JakeRabinowitz** [comment]
Yep, that second image is what I expected it to look like!

Ah right, my mistake on the 45 degrees! Thanks for correcting me.

**Comment by DmitriySalnikov** [comment]
Okay, it turns out there is an additional constructor in C++ that is not in GDScript.
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/4db4d8fc-4e39-48b7-8660-516947f7ca55)
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/8e866e1a-b0a0-40dc-b12f-70b46db7f9a2)

It was even easier to fix than I thought. 😅

**Comment by DmitriySalnikov** [comment]
Later, binaries for testing will appear [here](https://github.com/DmitriySalnikov/godot_debug_draw_3d/actions/runs/8164133856).

**Comment by JakeRabinowitz** [comment]
> Later, binaries for testing will appear [here](https://github.com/DmitriySalnikov/godot_debug_draw_3d/actions/runs/8164133856).

Looks like it works! Thanks so much for the quick fix!
