### ISSUE TITLE
[Bug]: DebugDrawDefaultCanvas Control Node filters mouse input

### ISSUE THREAD

**Issue by PauloVBettio** [DmitriySalnikov/godot_debug_draw_3d#39]
### Godot version

4.3.dev4.mono

### DebugDraw3D version

1.3.0

### On which operating systems the error occurs

Linux

### Using which renderers the error occurs

Vulkan

### Issue description

![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/74562432/118690b9-c053-4a4c-9e0e-148b1081e58f)

DebugDraw generates a Control node on top of the scene with the "Pass" mouse filter flag, which takes priority on every other node on the Scene.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by DmitriySalnikov** [comment]
What do you mean?

**Comment by PauloVBettio** [comment]
I apologize, investigating the problem I discovered that it is not in DebugDraw but in another plugin that is changing the value of other Control nodes. 🤦‍♂️
