### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by skooter500** [DmitriySalnikov/godot_debug_draw_3d#41]
### Godot version

4.2

### DebugDraw3D version

49df6b8d79a7861d8b3a4ef73280a5a4a743fcba

### Issue description

hey I love this plugin and use it in every project and for teaching every day

If I build to Android right now. the game crashes. Deleting the plugin and the game builds fine.

Godot 4.2 

### Steps to reproduce

Build for Pixel 6a and the game crashes back to home screen straight away

### Minimal reproduction project

https://github.com/skooter500/GP-2023

**Comment by skooter500** [comment]
Mobile Renderer
Forward+
Compatability

Also wont work in WebBuild

This is super useful to have for developing teaching exmples

**Comment by DmitriySalnikov** [comment]
I'm not sure what you're talking about. I found mentions of `DebugDraw2D` (you'd better provide a more compact and specific MRP), but I haven't encountered a crash.
I removed the comments and ran different scenes.
Used Debug and Release builds.
I also ran Web build and it worked as well.
I also spent half an hour just building the apk 😑

The main problem I encountered is that `sequencer.gd` is incorrectly named. The `sequencer.gd` is used, but the file is named `Sequencer.gd`. I renamed it and no longer saw any errors in the console.

![2024-03-10 09-00-49](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/15435cf6-9771-4225-887d-6c3b05860582)

![2024-03-10 09-15-34](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/f8d13ea6-198b-496d-b551-3e9f53ac7b80)

**Comment by skooter500** [comment]
here is a minimal project

https://github.com/skooter500/symmetrical-sniffle

When I install DebugDraw from assetlib and build for mobile, my app crashes straight after showing the Godot logo on my Pixel 6A. Same if I installed from git yesterday. When I remove DebugDraw it works.  Godot 4.2 Windows

**Comment by DmitriySalnikov** [comment]
This example doesn't give me anything. Therefore, other data is needed.

Please launch the application on your phone, run this command in the console in any folder and send the file `logs.txt`:
`adb logcat godot:V Godot:V GodotActivity:V DEBUG:V *:S -d > logs.txt`

If `adb` is not found, then `adb.exe` located in the `platform-tools` in the SDK folder.

**Comment by skooter500** [comment]
adb server is out of date.  killing...
* daemon started successfully *
--------- beginning of main
03-12 23:49:06.706 11488 11488 V GodotActivity: Creating new Godot fragment instance.
03-12 23:49:06.838 11488 11569 I godot   : Godot Engine v4.2.stable.official.46dc27791 - https://godotengine.org
03-12 23:49:06.865 11488 11569 I godot   : Vulkan API 1.3.219 - Forward Mobile - Using Vulkan Device #0: ARM - Mali-G78
03-12 23:49:08.213 11488 11569 I godot   :  
03-12 23:49:09.295 11488 11569 D Godot   : OnGodotSetupCompleted
03-12 23:49:09.296 11488 11569 D Godot   : OnGodotMainLoopStarted
--------- beginning of crash
03-12 23:49:10.659 11754 11754 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-12 23:49:10.659 11754 11754 F DEBUG   : Build fingerprint: 'google/bluejay/bluejay:13/TQ3A.230901.001/10750268:user/release-keys'
03-12 23:49:10.659 11754 11754 F DEBUG   : Revision: 'MP1.0'
03-12 23:49:10.659 11754 11754 F DEBUG   : ABI: 'arm64'
03-12 23:49:10.659 11754 11754 F DEBUG   : Timestamp: 2024-03-12 23:49:09.480876909+0000
03-12 23:49:10.659 11754 11754 F DEBUG   : Process uptime: 4s
03-12 23:49:10.659 11754 11754 F DEBUG   : Cmdline: ie.bryan.hello
03-12 23:49:10.659 11754 11754 F DEBUG   : pid: 11488, tid: 11569, name: VkThread  >>> ie.bryan.hello <<<
03-12 23:49:10.659 11754 11754 F DEBUG   : uid: 10369
03-12 23:49:10.659 11754 11754 F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
03-12 23:49:10.659 11754 11754 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000000
03-12 23:49:10.659 11754 11754 F DEBUG   : Cause: null pointer dereference
03-12 23:49:10.659 11754 11754 F DEBUG   :     x0  b400007677a8ce70  x1  0000000000000000  x2  0000007542911338  x3  0000007542911378
03-12 23:49:10.659 11754 11754 F DEBUG   :     x4  0000007542911368  x5  0000007542911358  x6  0000007542911348  x7  0000007542911648
03-12 23:49:10.659 11754 11754 F DEBUG   :     x8  b400007677a8ce70  x9  0000000000000008  x10 0000000000000000  x11 3f000000bf000000
03-12 23:49:10.659 11754 11754 F DEBUG   :     x12 3f000000bf000000  x13 3f000000bf000000  x14 0000007542910fa0  x15 0000000000000004
03-12 23:49:10.659 11754 11754 F DEBUG   :     x16 000000754fdce168  x17 00000078a0b96f20  x18 00000075425b0000  x19 0000007542911530
03-12 23:49:10.659 11754 11754 F DEBUG   :     x20 0000007542911648  x21 00000075429117ac  x22 0000000000000000  x23 0000000000000000
03-12 23:49:10.659 11754 11754 F DEBUG   :     x24 b400007677a8ce70  x25 0000000038d1b717  x26 b4000077078f5890  x27 00000075429117ac
03-12 23:49:10.659 11754 11754 F DEBUG   :     x28 0000003fff6f0810  x29 00000075429112b8
03-12 23:49:10.659 11754 11754 F DEBUG   :     lr  00000074bdaa04b4  sp  0000007542911230  pc  00000074bdaa0860  pst 0000000080001000
03-12 23:49:10.659 11754 11754 F DEBUG   : backtrace:
03-12 23:49:10.659 11754 11754 F DEBUG   :       #00 pc 00000000001d6860  /data/app/~~iEFboTwqe2CevvNhbvJUzQ==/ie.bryan.hello-cLwAK2ACg8oiYb4ZTh0zbw==/base.apk (offset 0x258000)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #01 pc 00000000001d64b0  /data/app/~~iEFboTwqe2CevvNhbvJUzQ==/ie.bryan.hello-cLwAK2ACg8oiYb4ZTh0zbw==/base.apk (offset 0x258000)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #02 pc 00000000001cec7c  /data/app/~~iEFboTwqe2CevvNhbvJUzQ==/ie.bryan.hello-cLwAK2ACg8oiYb4ZTh0zbw==/base.apk (offset 0x258000)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #03 pc 00000000001b40fc  /data/app/~~iEFboTwqe2CevvNhbvJUzQ==/ie.bryan.hello-cLwAK2ACg8oiYb4ZTh0zbw==/base.apk (offset 0x258000)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #04 pc 00000000001e3050  /data/app/~~iEFboTwqe2CevvNhbvJUzQ==/ie.bryan.hello-cLwAK2ACg8oiYb4ZTh0zbw==/base.apk (offset 0x258000)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #05 pc 0000000000192640  /data/app/~~iEFboTwqe2CevvNhbvJUzQ==/ie.bryan.hello-cLwAK2ACg8oiYb4ZTh0zbw==/base.apk (offset 0x258000)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #06 pc 0000000000086510  /data/app/~~iEFboTwqe2CevvNhbvJUzQ==/ie.bryan.hello-cLwAK2ACg8oiYb4ZTh0zbw==/base.apk (offset 0x258000)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #07 pc 00000000038177b8  /data/app/~~iEFboTwqe2CevvNhbvJUzQ==/ie.bryan.hello-cLwAK2ACg8oiYb4ZTh0zbw==/base.apk!libgodot_android.so (offset 0x450000)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #08 pc 0000000003856f8c  /data/app/~~iEFboTwqe2CevvNhbvJUzQ==/ie.bryan.hello-cLwAK2ACg8oiYb4ZTh0zbw==/base.apk!libgodot_android.so (offset 0x450000)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #09 pc 0000000003557008  /data/app/~~iEFboTwqe2CevvNhbvJUzQ==/ie.bryan.hello-cLwAK2ACg8oiYb4ZTh0zbw==/base.apk!libgodot_android.so (offset 0x450000)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #10 pc 000000000385127c  /data/app/~~iEFboTwqe2CevvNhbvJUzQ==/ie.bryan.hello-cLwAK2ACg8oiYb4ZTh0zbw==/base.apk!libgodot_android.so (offset 0x450000)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #11 pc 00000000038518d8  /data/app/~~iEFboTwqe2CevvNhbvJUzQ==/ie.bryan.hello-cLwAK2ACg8oiYb4ZTh0zbw==/base.apk!libgodot_android.so (offset 0x450000)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #12 pc 0000000001a74c68  /data/app/~~iEFboTwqe2CevvNhbvJUzQ==/ie.bryan.hello-cLwAK2ACg8oiYb4ZTh0zbw==/base.apk!libgodot_android.so (offset 0x450000)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #13 pc 0000000000e5cbdc  /data/app/~~iEFboTwqe2CevvNhbvJUzQ==/ie.bryan.hello-cLwAK2ACg8oiYb4ZTh0zbw==/base.apk!libgodot_android.so (offset 0x450000)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #14 pc 0000000000e193e8  /data/app/~~iEFboTwqe2CevvNhbvJUzQ==/ie.bryan.hello-cLwAK2ACg8oiYb4ZTh0zbw==/base.apk!libgodot_android.so (offset 0x450000)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #15 pc 0000000000e2d6b4  /data/app/~~iEFboTwqe2CevvNhbvJUzQ==/ie.bryan.hello-cLwAK2ACg8oiYb4ZTh0zbw==/base.apk!libgodot_android.so (offset 0x450000) (Java_org_godotengine_godot_GodotLib_step+220)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #16 pc 0000000000355630  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+144) (BuildId: 41ac8dfed2977c7a168799976d23a7f8)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #17 pc 000000000033ee80  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640) (BuildId: 41ac8dfed2977c7a168799976d23a7f8)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #18 pc 0000000000512bc8  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+2364) (BuildId: 41ac8dfed2977c7a168799976d23a7f8)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #19 pc 00000000004935b4  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+1892) (BuildId: 41ac8dfed2977c7a168799976d23a7f8)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #20 pc 0000000000357dd8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 41ac8dfed2977c7a168799976d23a7f8)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #21 pc 00000000001981ec  [anon:dalvik-classes.dex extracted in memory from /data/app/~~iEFboTwqe2CevvNhbvJUzQ==/ie.bryan.hello-cLwAK2ACg8oiYb4ZTh0zbw==/base.apk] (org.godotengine.godot.vulkan.VkRenderer.onVkDrawFrame+0)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #22 pc 0000000000371b14  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.8722505846101882172)+232) (BuildId: 41ac8dfed2977c7a168799976d23a7f8)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #23 pc 0000000000513710  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+5252) (BuildId: 41ac8dfed2977c7a168799976d23a7f8)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #24 pc 0000000000493244  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+1012) (BuildId: 41ac8dfed2977c7a168799976d23a7f8)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #25 pc 0000000000357dd8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 41ac8dfed2977c7a168799976d23a7f8)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #26 pc 000000000019899c  [anon:dalvik-classes.dex extracted in memory from /data/app/~~iEFboTwqe2CevvNhbvJUzQ==/ie.bryan.hello-cLwAK2ACg8oiYb4ZTh0zbw==/base.apk] (org.godotengine.godot.vulkan.VkThread.run+0)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #27 pc 0000000000371b14  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.8722505846101882172)+232) (BuildId: 41ac8dfed2977c7a168799976d23a7f8)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #28 pc 000000000037140c  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+964) (BuildId: 41ac8dfed2977c7a168799976d23a7f8)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #29 pc 0000000000355768  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 41ac8dfed2977c7a168799976d23a7f8)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #30 pc 000000000033eba4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: 41ac8dfed2977c7a168799976d23a7f8)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #31 pc 000000000023a9ac  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+144) (BuildId: 41ac8dfed2977c7a168799976d23a7f8)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #32 pc 000000000053b98c  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1600) (BuildId: 41ac8dfed2977c7a168799976d23a7f8)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #33 pc 000000000053b33c  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallbackWithUffdGc(void*)+8) (BuildId: 41ac8dfed2977c7a168799976d23a7f8)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #34 pc 00000000000c226c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: dc4001c2ef2dfc23467040797a96840c)
03-12 23:49:10.659 11754 11754 F DEBUG   :       #35 pc 0000000000054a30  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: dc4001c2ef2dfc23467040797a96840c)

**Comment by skooter500** [comment]
A link to download the file https://drive.google.com/file/d/1HtBu1eVr2R1EkQSMAN9M4oIph0rURgcE/view?usp=sharing

**Comment by DmitriySalnikov** [comment]
> adb server is out of date. killing...

you can use this construction (with ``` or `) to insert code or unformatted text:

![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/c176f0ce-a11b-43bf-ae1e-1eeddd174125)


> A link to download the file

Just drag and drop the file (< 10MB) into the text box next time.

> https://drive.google.com/file/d/1HtBu1eVr2R1EkQSMAN9M4oIph0rURgcE/view?usp=sharing

There is nothing explicit about my library here. But if you managed to build the APK, then most likely all the libraries are correctly copied to the APK. The only thing I can assume is that you may have different versions of android libraries and the version of the engine. You can provide the entire minimal project folder with all the files, as well as a debugging APK (if it doesn't work either).

But at the moment I don't see any problems with my library.

**Comment by skooter500** [comment]
Ok The issue is that it runs fine with the .Net version of Godot, but crashes on Android when I build with the plain version of Godot that doesnt come with /net/c#

**Comment by GeorgeS2019** [comment]
@skooter500 
Can you try the c# wrappers generated for GodotDebugDraw3D.
I tried other wrapper. seems to work fine
https://github.com/Delsin-Yu/CSharp-Wrapper-Generator-for-GDExtension
