### ISSUE TITLE
[Feature Request]: Set Render priority

### ISSUE THREAD

**Issue by bluelightzero** [DmitriySalnikov/godot_debug_draw_3d#44]
### Feature description

My scene makes use of a post-processing quad.

This means that any debug draw geometry gets put through the same post processing.

Ideally I would not like it to affect any of the debug lines drawn. It darkens them too much making them less useful.

If I had control over the material of the debug lines, I would simply enable transparency and increase the render priority 

![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/4492982/64ff1d06-41ab-438c-92bb-8769278ebbcd)

 - Post process represented as yellow
 - Left quad representing debug draw material desired. (render priority increased and transparency enabled)
 - Right quad representing current debug draw material.

### Implementation Ideas

A simple project setting to set these 2 properties would be all I need.

**Comment by DmitriySalnikov** [comment]
Which properties exactly do you want to change?

**Comment by bluelightzero** [comment]
> Which properties exactly do you want to change?

render priority increased and transparency enabled

> I also wonder if disabling the depth test helps?

It draws over my post-process now, but also just draws over everything.

![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/4492982/c0cc243f-41e3-4a42-a93f-428fabdca581)

![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/4492982/eaf41c99-95ce-4693-98d7-52af218177f3)

**Comment by DmitriySalnikov** [comment]
> render priority increased and transparency enabled

I was referring to the names of the properties in the shaders. I have not found how to increase the priority.

I know how to enable transparency mode, but I don't really understand how to change the priority.

**Comment by bluelightzero** [comment]
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/4492982/68ebf34e-501d-46c1-8b17-ccfd7ca0a257)

**Comment by bluelightzero** [comment]
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/4492982/ecd283e5-ce66-454d-98dc-ed8eb6fdf591)

![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/4492982/371e4508-096a-4bd5-9a17-b175d76c45b0)

**Comment by DmitriySalnikov** [comment]
(here `regenerate_geometry_meshes` is used when clicking on END)

https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/ad280292-4677-42d6-84e8-24d890c61a8e

I don't like the fact that transparent shapes are not sorted among themselves by distance to the camera :(

**Comment by bluelightzero** [comment]
Looks like the setting is working well.  :)

Is this going in a build soon?

**Comment by DmitriySalnikov** [comment]
[Test binaries will be here](https://github.com/DmitriySalnikov/godot_debug_draw_3d/actions/runs/9176621965)

**Comment by DmitriySalnikov** [comment]
> https://www.khronos.org/opengl/wiki/Transparency_Sorting

I'm not sure, but it probably doesn't suit me, because I use `MultiMesh`, which are sorted once for all instances based on the node/mesh position (and the position of all of them is `Vector3(0,0,0)`...). Perhaps some combination of flags and shader code can fix this problem, but I did not succeed. If I understand correctly, then the best solution would be to use individual instances for each shape when using `no_depth` or `transparent` materials, which will decrease performance and require a lot of code edits.

Is the current renderer priority solution suitable for you?
