### ISSUE TITLE
[Feature Request]: Statically link libgcc and libstdc++ on linux

### ISSUE THREAD

**Issue by goatchurchprime** [DmitriySalnikov/godot_debug_draw_3d#45]
### Feature description

This library doesn't work under nixos due to the libstdc++ library not being statically linked.  

There might be similar portability issues to other linux distros.  

![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/677254/3f57e88d-ebec-48ff-9dcc-e93c2e55ad55)

This was noted for the webrtc plugin:  https://github.com/godotengine/webrtc-native/issues/110

### Implementation Ideas

The fix was a couple of settings in the SConstruct file to force static linking to the libstdc++ libraries.
https://github.com/godotengine/webrtc-native/pull/109/commits/1de32aa9ea1f3f4e1fd3f5f9b283ac4dc2befae1

**Comment by DmitriySalnikov** [comment]
> There might be similar portability issues to other linux distros.

Sure.
I have already faced another problem. My library refused to run on Ubuntu 20 if the library was built on Ubuntu 22. I found these build flags, but as far as I remember it still didn't solve the problem, so I just rolled back the Ubuntu version inside Github CI and everything worked.

You can test these changes [here](https://github.com/DmitriySalnikov/godot_debug_draw_3d/actions/runs/9244307106)

😔
![fkP4hntFE7](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/9c7f6104-4714-4200-95e6-997a3ec04a8e)

**Comment by DmitriySalnikov** [comment]
@goatchurchprime so is the library working now?

**Comment by goatchurchprime** [comment]
Confirmed that April version does not work, and this May version does work.  
I think @Nitwel had sent me a fixed version that he compiled himself, it worked, and then I completely forgot about it.
