### ISSUE TITLE
[Bug]: Web Exports fail in 4.3beta2

### ISSUE THREAD

**Issue by zaknafean** [DmitriySalnikov/godot_debug_draw_3d#46]
### Godot version

4.3 beta 2

### DebugDraw3D version

4.1.3

### On which operating systems the error occurs

Web

### Using which renderers the error occurs

Vulkan

### Issue description

This MAY not be an issue with your plugin specifically, but figured I'd report it anyway, for awareness if nothing else. Troubleshooting a gamejam export with Godot 4.3 beta 2, and after checking the extensions support box:
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7741797/cdfc12c8-d246-4d73-aa10-57d706402d50)

Any attempt to run the project from a browser resulted in  this error
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7741797/08341533-7cc4-4400-aa13-fe015c58d1c7)

After trial and error turning on and off a number of plugins, the only fix was to remove the DebugDraw from my release build.

As I'm not using any other GDextension plugins, I don't know if this is a wider issue with GDExtensions and web exports as a whole, or specific to this project. If so, a note or warning to users may be warranted as the error was hard to figure out.

Windows exports were working perfectly fine with no issues.

### Steps to reproduce

1) Create a game and include DebugDraw3D in **Godot 4.3 beta2**
2) Export via web after checking the GD Extension button
3) The game will hang with the above error.

### Minimal reproduction project

N/A

**Comment by DmitriySalnikov** [comment]
> ### DebugDraw3D version
> 4.1.3

This is not the DD3D version, this is the minimum version of Godot that it supports.

> ### Godot version
> 4.3 beta 2

Godot 4.3 has not been released yet. There have been a lot of changes related to WebAssembly and if this is a real problem, then I will have to change the minimum version from 4.1.3 to 4.3, which I would not like to do.

**Comment by zaknafean** [comment]
My mistake. I'm using 1.4.1 of DD3D
![image](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7741797/ca8482a1-c0f7-4553-9298-45395e1175fd)

I can try to see if 1.4.2 fixes the issue. But I expect it is just a web export problem that's probably more on the Godot side.

**Comment by DmitriySalnikov** [comment]
Fixed in 72e3b52adffedadd3e5f8d0c7384ca58227102d0
