### ISSUE TITLE
[Feature Request]: ignore environment/fog/postprocessing

### ISSUE THREAD

**Issue by Sythelux** [DmitriySalnikov/godot_debug_draw_3d#48]
### Feature description

I have set an environment with fog, which will make the debug lines be blended out the further away they are.
Example how it looks like rn:
![Bildschirmfoto vom 2024-06-30 13-01-57](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/601797/51092097-4986-478c-86a2-480a4c20d18b)

### Implementation Ideas

I would like a setting, to let debug3D bypass the environment and have it always visible. unfortunately the fix for #44 doesn't help or I'm to stupid to use it correctly.

example how it looks without fog enabled, which would be cool to have always:
![grafik](https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/601797/d1590027-5df2-4be7-9196-71de00b9761f)

**Comment by DmitriySalnikov** [comment]
https://github.com/DmitriySalnikov/godot_debug_draw_3d/assets/7782218/15b9ef8b-c98d-40d0-a08e-c3186c3f2b14

[Test binaries](https://github.com/DmitriySalnikov/godot_debug_draw_3d/actions/runs/9734614603)
