### ISSUE TITLE
[Bug]: Editor instantly crashes on opening

### ISSUE THREAD

**Issue by Paraxodon** [DmitriySalnikov/godot_debug_draw_3d#52]
### Godot version

4.2.2-stable_win64 (also in 4.3)

### DebugDraw3D version

1.4.4

### On which operating systems the error occurs

Windows

### Using which renderers the error occurs

Vulkan

### Issue description

Every time I add the plugin into my project the editor crashes instantly, and when i try to open it it crashes too, without any kind of logs.

### Steps to reproduce

1. Add the "debug_draw_3d" folder into "addons".
2. Crash.
3. Try to open again.
4. Crash.
5. Remove "debug_draw_3d" folder.
6. Stops crashing.

### Minimal reproduction project

[debugdrawcrash.zip](https://github.com/user-attachments/files/16695575/debugdrawcrash.zip)

**Comment by Paraxodon** [comment]
I'd like to add that it only happens in my windows laptop, in my work linux laptop it works nicely.
Also it happens in compatibility mode too.

**Comment by Paraxodon** [comment]
![image](https://github.com/user-attachments/assets/c71b9324-c98b-4870-a013-b9482b0b746b)
This is the only thing shown before crashing.
![image](https://github.com/user-attachments/assets/e08ff46a-7d61-49df-bd45-5642ca9655d5)
And this is the logs folder.

**Comment by DmitriySalnikov** [comment]
Oh, unexpectedly.. Try this version:

https://github.com/DmitriySalnikov/godot_debug_draw_3d/actions/runs/10496169989

**Comment by Paraxodon** [comment]
Ok, reading through other issues i found out you added the telemetry module just after 1.2, so i tried with that version and it now works, something is wrong with the telemetry. 
Let me read through the other issue to find a way to compile 1.3-1.4 without telemetry to confirm this is the issue, but it seems like it.

**Comment by DmitriySalnikov** [comment]
I have already compiled it without telemetry https://github.com/DmitriySalnikov/godot_debug_draw_3d/actions/runs/10496169989

**Comment by Paraxodon** [comment]
Well, I spent 1 hour learning how "scons" works... (it was just two commands but my experience with any installation through windows is quite horrendous, most of my time was wasted realizing I have two different python installations and one of them wasn't in the system variables, so scons wasn't working) but i finally compiled it by myself.
 Probably if i had bothered to check your quick response (which I really appreciate, as well as the creation of this plugin which is fucking awesome and i love you for making it) I wouldn't have wasted 1 hour, but hey, now I know a little more about gdextension, which is nice.
 So for the answer, now it works, it was the telemetry. If you have any idea what could be happening and how can i help you if you want to fix it do not hesitate to contact me, since i really appreciate this plugin and any help i can provide is cool.

**Comment by DmitriySalnikov** [comment]
I tried redirecting DNS to 0.0.0.0 via the hosts file. I tried to drop 100% of packets to create a timeout error, tried to enter incorrect domains, tried to corrupt traffic.
But the most unusual thing I got was an TLS error.
![WindowsTerminal_Pw5qpB0pS4](https://github.com/user-attachments/assets/f8d77ba6-e324-4682-be28-748b63713106)

Therefore, I still have no idea what exactly leads to the crash.

---

@Paraxodon I compiled the debug version, added a bunch of markers and attached a PDB file. Can you run this version and show the console output?
[libdd3d.windows.editor.x86_64.zip](https://github.com/user-attachments/files/16708801/libdd3d.windows.editor.x86_64.zip)

![image](https://github.com/user-attachments/assets/3efeb36c-db74-42f9-9e15-67bfc8e9ffba)

**Comment by Paraxodon** [comment]
![image](https://github.com/user-attachments/assets/119d988c-b3a6-4382-8b4d-3867ccebd41b)
This is what I get before it instantly crashes. Do you need to know my specific hardware?

**Comment by DmitriySalnikov** [comment]
> Do you need to know my specific hardware?

The crash happens somewhere around parsing `OS.get_locale()`. It seems you live outside any country...
I'm actually interested in what `OS.get_locale()` outputs for you.

Here is most likely a fully working **debug** version:
[libdd3d.windows.editor.x86_64.zip](https://github.com/user-attachments/files/16717012/libdd3d.windows.editor.x86_64.zip)
