### ISSUE TITLE
[Bug]: Spurious GDScript compiler errors after install

### ISSUE THREAD

**Issue by hsandt** [DmitriySalnikov/godot_debug_draw_3d#55]
### Godot version

v4.3.stable.official [77dcf97d8]

### DebugDraw3D version

1.4.4

### On which operating systems the error occurs

Linux

### Using which renderers the error occurs

GLES3

### Issue description

After install, I am spammed with these errors:

> modules/gdscript/gdscript_compiler.cpp:123 - GDScript bug: Native class "DebugDraw3DScopeConfig" not found.
  modules/gdscript/gdscript_compiler.cpp:123 - GDScript bug: Native class "DebugDraw3DScopeConfig" not found.
  res://examples_dd3d/addon_icon.gd:5 - Compile Error: Identifier not found: DebugDraw3D
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://examples_dd3d/addon_icon.gd" with error "Compilation failed". (User)
  res://examples_dd3d/DebugDrawDemoScene.gd:71 - Compile Error: Identifier not found: DebugDraw3D
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://examples_dd3d/DebugDrawDemoScene.gd" with error "Compilation failed". (User)
  modules/gdscript/gdscript_compiler.cpp:123 - GDScript bug: Native class "DebugDraw3DScopeConfig" not found.
  modules/gdscript/gdscript_compiler.cpp:123 - GDScript bug: Native class "DebugDraw3DScopeConfig" not found.
  modules/gdscript/gdscript_compiler.cpp:123 - GDScript bug: Native class "DebugDraw3DScopeConfig" not found.
  res://examples_dd3d/demo_music_visualizer.gd:128 - Compile Error: Identifier not found: DebugDraw3D
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://examples_dd3d/demo_music_visualizer.gd" with error "Compilation failed". (User)
  modules/gdscript/gdscript_compiler.cpp:123 - GDScript bug: Native class "DebugDraw2DGraph" not found.
  modules/gdscript/gdscript_compiler.cpp:123 - GDScript bug: Native class "DebugDraw2DGraph" not found.
  modules/gdscript/gdscript_compiler.cpp:123 - GDScript bug: Native class "DebugDraw2DGraph" not found.
  res://examples_dd3d/demo_settings_panel.gd:16 - Compile Error: Identifier not found: DebugDraw2D
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://examples_dd3d/demo_settings_panel.gd" with error "Compilation failed". (User)

They must be spurious because when I try some example lines, they do work.

### Steps to reproduce

Install v1.4.4 in some Godot project, observe output.

### Minimal reproduction project

N/A

**Comment by DmitriySalnikov** [comment]
You can remove the examples when unpacking and there will be no errors.
![image](https://github.com/user-attachments/assets/24093059-bf31-4791-a26c-571ed00a7f01)

These are engine errors, I do not know how to fix it.

Anyway, you will need to restart the editor in order for the addon to work inside the editor.
